# Generated by Django 4.2.5 on 2023-09-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name_plural': 'Agent'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiry'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'Listing'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Property'},
        ),
        migrations.AddField(
            model_name='property',
            name='photo1',
            field=models.ImageField(null=True, upload_to='property_photos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo2',
            field=models.ImageField(null=True, upload_to='property_photos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo3',
            field=models.ImageField(null=True, upload_to='property_photos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo4',
            field=models.ImageField(null=True, upload_to='property_photos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo5',
            field=models.ImageField(null=True, upload_to='property_photos/'),
        ),
    ]
