# Generated by Django 4.2.5 on 2023-09-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_alter_agent_options_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sqft',
        ),
        migrations.AddField(
            model_name='property',
            name='Agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=1, upload_to='property_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
