# Generated by Django 4.2.5 on 2023-10-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
    ]
